### PR TITLE
Showcase of shasum-summary tool

### PR DESCRIPTION
**Pull request by 0xB10C**
Shows:

- mismatches in `27.0` from https://github.com/bitcoin-core/guix.sigs/pull/1197 
- single (artificial) mismatch in `22.0`
- (artificially) missing artifacts from `23.0`
- (existing) non-determinism in `26.0rc1`

### CODE REVIEW

**Comment by laanwj** [comment]
Nice !!!

> hash mismatch: one of ░, ▞, ▄, ▀, ▌, ▐, ▚

i suppose these are different groups of mismatching hashes? eg the same glyph will match each other, but not different ones?

**Comment by 0xB10C** [comment]
Correct, that's whats happening in the first example. With enough different hashes they will start to repeat but at that point there's enough non-determinism that we are aware of it anyway and need to manually check.

**Comment by laanwj** [comment]
> Correct, that's whats happening in the first example. With enough different hashes they will start to repeat but at that point there's enough non-determinism that we are aware of it anyway and need to manually check.

Thanks. Yea... that means something is very wrong,

BTW, `░` looks very much like an empty square here (which i'd interpret as "missing").

**Comment by 0xB10C** [comment]
> BTW, ░ looks very much like an empty square here (which i'd interpret as "missing").

Good point. Could use e.g ◆ instead.

**Comment by 0xB10C** [comment]
https://github.com/bitcoin-core/guix.sigs/pull/1207 was merged. Closing.

**Pull request closed without merging**
